let brand = "Ford";
console.log(brand);
let model = "Mustang";
console.log(model);
let productionDate = 1970;
console.log(productionDate);
let maxSpeed = 250;
console.log(maxSpeed);
let countryOfProduction = "USA";
console.log(countryOfProduction);
